src/MVC/Models/ErrorViewModel.cs
namespace MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/MVC/ViewModels/ProductCreateViewModel.cs
using Core.Models;

namespace MVC.ViewModels
{
    public class ProductCreateViewModel
    {
       public Product Product { get; set; } = new Product();
        public List<Category>? Categories { get; set; }
    }
}

src/MVC/Areas/Admin/Controllers/CategoryController.cs
using Business.Services.Interfaces;
using Core.Models;
using Microsoft.AspNetCore.Mvc;

namespace MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService CategoryService)
        {

            _categoryService = CategoryService;

        }

        public async Task<IActionResult> Index()
        {
            return View(await _categoryService.GetAllCategories());
        }

        public async Task<IActionResult> Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(Category model)
        {
            if (! ModelState.IsValid) return View();
        

            await _categoryService.CreateNewCategory(model);

            return RedirectToAction(nameof(Index));


        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id) {

            await _categoryService.DeleteCategory(id);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Update(int id)
        {
            Category? old = await _categoryService.GetById(id);

            if(old is null) return BadRequest();
           
            return View(old);


        }
        [HttpPost]
        public async Task<IActionResult> Update(Category category)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("Name", "Name Error");
                return View(category);
            };

            await _categoryService.UpdateCategory(category);

            return RedirectToAction(nameof(Index));
        }
    }
}

src/MVC/Areas/Admin/Controllers/DashboardController.cs
using Business.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {

        public async Task<IActionResult> Index()
        {
            return View();
        }
    }
}

src/MVC/Areas/Admin/Controllers/ProductController.cs
using Business.Services.Interfaces;
using Core.Models;
using Microsoft.AspNetCore.Mvc;
using MVC.ViewModels;

namespace MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        public ProductController(IProductService productService, ICategoryService categoryService)
        {
            _productService = productService;
            _categoryService = categoryService;
        }


        public async Task<IActionResult> Index()
        {
            return View(await _productService.GetAllProducts()) ;
        }

        public async Task<IActionResult> Create()
        {
            return View(new ProductCreateViewModel() { 
                Categories = await _categoryService.GetAllCategories()
            });
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProductCreateViewModel entity)
        {

            await _productService.CreateNewProduct(entity.Product);

            if (!ModelState.IsValid) return View(new ProductCreateViewModel
            {
                Categories = await _categoryService.GetAllCategories()
            });


            return RedirectToAction(nameof(Index));
        }
    } 
}

src/MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC.Models;
using System.Diagnostics;

namespace MVC.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/MVC/Areas/Admin/Views/Category/Create.cshtml
@using Core.Models;
@model Category

<form method="POST" asp-action="Create" asp-controller="Category">

    <div class="mb-3">
        <label asp-for='Name'  class="form-label">Name</label>
        <input asp-for='Name'  class="form-control">
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
 
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

src/MVC/Areas/Admin/Views/Category/Index.cshtml
@using Core.Models;
@model List<Category>?

<div class="container-fluid">




<table class="table">
        <a class="btn btn-success my-4" asp-action="Create" asp-controller="Category">Create</a>
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">NAME</th>
            <th>ACTIONS</th>
   
        </tr>
    </thead>
    <tbody>

            @foreach(Category c in Model)
            {
                <tr>
                    <th>@c.Id</th>
                    <td>@c.Name</td>
                    <th>
                        <a asp-action="Update" asp-controller="Category" asp-route-id="@c.Id" class="btn btn-warning">UPDATE</a>
                        <form asp-action="Delete" asp-controller="Category" asp-route-id="@c.Id" method="POST">
                            <button class="btn btn-danger">DELETE</button>
                        </form>
                    </th>
                </tr>

            }


      
    </tbody>
</table>


</div>

src/MVC/Areas/Admin/Views/Category/Update.cshtml
@using Core.Models;
@model Category

<form method="POST" asp-action="Update" asp-controller="Category">

    <div class="mb-3">
        <label asp-for='Name' class="form-label">Name</label>
        <input asp-for='Name' class="form-control">
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

src/MVC/Areas/Admin/Views/Dashboard/Index.cshtml
<h1 class="display-1">YOO! NICE TO MEET YA</h1>

src/MVC/Areas/Admin/Views/Product/Create.cshtml
@using Core.Models;
@using MVC.ViewModels;
@model ProductCreateViewModel

<form method="POST" asp-action="Create" asp-controller="Product" enctype="multipart/form-data">

    <div class="mb-3">
        <label asp-for='@Model.Product.ShowcasePrimaryText' class="form-label"></label>
        <input asp-for='@Model.Product.ShowcasePrimaryText' class="form-control">
        <span class="text-danger" asp-validation-for="@Model.Product.ShowcasePrimaryText"></span>
    </div>

    <div class="mb-3">
        <label asp-for='@Model.Product.ShowcaseSecondaryText' class="form-label"></label>
        <input asp-for='@Model.Product.ShowcaseSecondaryText' class="form-control">
        <span class="text-danger" asp-validation-for="@Model.Product.ShowcaseSecondaryText"></span>
    </div>


    <div class="mb-3">
        <label asp-for='@Model.Product.ProjectName' class="form-label"></label>
        <input asp-for='@Model.Product.ProjectName' class="form-control">
        <span class="text-danger" asp-validation-for="@Model.Product.ProjectName"></span>
    </div>


    <div class="mb-3">
        <label asp-for='@Model.Product.Description' class="form-label"></label>
        <input asp-for='@Model.Product.Description' class="form-control">
        <span class="text-danger" asp-validation-for="@Model.Product.Description"></span>
    </div>

    <div class="mb-3">
        <label asp-for='@Model.Product.MiniDescription' class="form-label"></label>
        <input asp-for='@Model.Product.MiniDescription' class="form-control">
        <span class="text-danger" asp-validation-for="@Model.Product.MiniDescription"></span>
    </div>


    <div class="mb-3">
        <select asp-for="@Model.Product.CategoryId">
            @foreach(Category category in Model.Categories)
        {
            <option value="@category.Id">
                @category.Name               
            </option>
        }

        </select>


    </div>


    <div class="mb-3">
        <label asp-for='@Model.Product.ProductImage' class="form-label"></label>
        <input asp-for='@Model.Product.ProductImage' class="form-control">
        <span class="text-danger" asp-validation-for="@Model.Product.ProductImage"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

src/MVC/Areas/Admin/Views/Product/Index.cshtml
@using Core.Models;

@model List<Product>?

<div class="container-fluid">




    <table class="table">
        <a class="btn btn-success my-4" asp-action="Create" asp-controller="Product">Create</a>
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">ShowcasePrimaryText</th>
                <th scope="col">ShowcaseSecondaryText</th>
                <th scope="col">ProjectName</th>
                <th scope="col">Description</th>
                <th scope="col">MiniDescription</th>
                <th scope="col">ImageFileName</th>
                <th scope="col">CategoryId</th>
                <th>ACTIONS</th>

            </tr>
        </thead>
        <tbody>

            @foreach (Product c in Model)
            {
                <tr>
                    <th scope="col">@c.</th>
                    <th scope="col">ShowcaseSecondaryText</th>
                    <th scope="col">ProjectName</th>
                    <th scope="col">Description</th>
                    <th scope="col">MiniDescription</th>
                    <th scope="col">ImageFileName</th>
                    <th scope="col">CategoryId</th>
                    <th>
                        <a asp-action="Update" asp-controller="Category" asp-route-id="@c.Id" class="btn btn-warning">UPDATE</a>
                        <form asp-action="Delete" asp-controller="Category" asp-route-id="@c.Id" method="POST">
                            <button class="btn btn-danger">DELETE</button>
                        </form>
                    </th>
                </tr>

            }



        </tbody>
    </table>


</div>

src/MVC/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="/admin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="/admin/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="index.html">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Interface
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Components</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Custom Components:</h6>
                        <a class="collapse-item" href="buttons.html">Buttons</a>
                        <a class="collapse-item" href="cards.html">Cards</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                   aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Utilities</span>
                </a>
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Custom Utilities:</h6>
                        <a class="collapse-item" href="utilities-color.html">Colors</a>
                        <a class="collapse-item" href="utilities-border.html">Borders</a>
                        <a class="collapse-item" href="utilities-animation.html">Animations</a>
                        <a class="collapse-item" href="utilities-other.html">Other</a>
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Addons
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
                   aria-expanded="true" aria-controls="collapsePages">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>Pages</span>
                </a>
                <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Login Screens:</h6>
                        <a class="collapse-item" href="login.html">Login</a>
                        <a class="collapse-item" href="register.html">Register</a>
                        <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
                        <div class="collapse-divider"></div>
                        <h6 class="collapse-header">Other Pages:</h6>
                        <a class="collapse-item" href="404.html">404 Page</a>
                        <a class="collapse-item" href="blank.html">Blank Page</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="charts.html">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Charts</span>
                </a>
            </li>

            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link" href="tables.html">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Tables</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

            <!-- Sidebar Message -->
            <div class="sidebar-card d-none d-lg-flex">
                <img class="sidebar-card-illustration mb-2" src="/admin/img/undraw_rocket.svg" alt="...">
                <p class="text-center mb-2"><strong>SB Admin Pro</strong> is packed with premium features, components, and more!</p>
                <a class="btn btn-success btn-sm" href="https://startbootstrap.com/theme/sb-admin-pro">Upgrade to Pro!</a>
            </div>

        </ul>
        <!-- End of Sidebar -->

        @RenderBody()



    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="/admin/vendor/jquery/jquery.min.js"></script>
    <script src="/admin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="/admin/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="/admin/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="/admin/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="/admin/js/demo/chart-area-demo.js"></script>
    <script src="/admin/js/demo/chart-pie-demo.js"></script>

</body>

</html>

src/MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Agency - Start Bootstrap Theme</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="/asets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="/css/styles.css" rel="stylesheet" />
</head>
<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="#page-top"><img src="/assets/img/" alt="..." /></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars ms-1"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link" href="#services">Services</a></li>
                    <li class="nav-item"><a class="nav-link" href="#portfolio">Portfolio</a></li>
                    <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                    <li class="nav-item"><a class="nav-link" href="#team">Team</a></li>
                    <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    @RenderBody()



    <!-- Footer-->
    <footer class="footer py-4">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-4 text-lg-start">Copyright &copy; Your Website 2023</div>
                <div class="col-lg-4 my-3 my-lg-0">
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Twitter"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
                </div>
                <div class="col-lg-4 text-lg-end">
                    <a class="link-dark text-decoration-none me-3" href="#!">Privacy Policy</a>
                    <a class="link-dark text-decoration-none" href="#!">Terms of Use</a>
                </div>
            </div>
        </div>
    </footer>



    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="/js/scripts.js"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>
</html>